### ISSUE TITLE
The docs published on pook.rtfd.io seem to be outdated (latest == 0.2.5)

### ISSUE THREAD

**Issue by petarmaric** [h2non/pook#118]
Looking at both the page title and contents of https://pook.readthedocs.io/en/latest/history.html it seems that the latest version is 0.2.5, which has been [published some 6 years ago](https://pypi.org/project/pook/0.2.5/). And we've had [1.4.1 released just a few hours ago](https://pypi.org/project/pook/#history) :+1: 

Can you please update the official docs at https://pook.rtfd.io to include newer/latest version of pook? Thanks.

**Comment by sarayourfriend** [comment]
@h2non Might need your help on this one. I've pushed configuration for RTD to `master`, but I'm not seeing it pick up a new build: https://readthedocs.org/projects/pook/builds/. Is there any configuration on the RTD dashboard that needs to be updated? If it's possible to add me to the pook project on RTD, that would help get the docs fixed and updated. My username there is the same as here.

**Comment by sarayourfriend** [comment]
RTD docs are updated with the latest code: https://pook.readthedocs.io/en/latest/

v1.4.1 won't build docs correctly (because the `.readthedocs.yaml` file doesn't exist on that tag yet) so there won't be a tagged version available until the next release.
