### ISSUE TITLE
Capture and replay requests

### ISSUE THREAD

**Issue by piranna** [h2non/pook#137]
Node.js `nock` has an option to capture real requests, write them in files, and later use them as fixtures instead of doing the actual network requests. This is REALLY useful to movk third-party servers. Is there any way of generate these automated fixtures with `pook`?

**Comment by sarayourfriend** [comment]
This is not supported in pook.

As far as I know, the standard library to use for this with Python is the Python port of Ruby's popular VCR library: https://github.com/kevin1024/vcrpy

I'm going to close this as won't do. vcrpy fulfils this use case and is well maintained, there's no reason for pook to incorporate this functionality, particularly as pook approaches request testing with a slightly different angle.

**Comment by piranna** [comment]
It looks like `pook` is into mocking, meanwhile `vrcpy` is into generate and use fixtures, and at the same time `nock` have implemented both aproaches, isn't it? I like `nock` concept of generating the fixtures as API calls, so later they can be modified, although that could be improved.

Not sure if it would be better a tool to convert `vrcpy` cassetes into `pook` mocks, or filter the data of `vrcpy` fixtures for customized values, maybe it already has support for it...

**Comment by sarayourfriend** [comment]
What I've done on WordPress/Openverse, where we use the Node library Talkback for the same thing in Playwright tests, is record the "tapes" as usual, and then edit them afterwards to suit niche purposes.

Pook is good for asserting particular parameters are sent, and easily mocking some kind of response. You could use vcrpy to create those fixtures and then pass them to pook, if you need both at the same time. To me, these libraries serve distinct purposes, and vcrpy solves the problem well with years of development, maintenance, and support. At the current level of contribution and maintenance, pook needs to focus on its core purpose.

Pook has some points of extensibility, like custom matchers, request filters and mappers, and the network filters. If you feel strongly that pook must be the single entrypoint for both approaches to testing and mocking requests, please try seeing if these existing points of extensibility allow you to incorporate vcrpy, and if additional extensibility is required, I'm happy to review proposals for those to see if they fit into the project. We've incorporated such extensibility in the past to support integration with other testing libraries (e.g., https://github.com/h2non/pook/issues/33)

**Comment by piranna** [comment]
I think vcrpy can do the job for my use case, since It has filters too. Now looking for an alternative for WebSockets and SSE and ideally TCP sockets (my app is "complex"... :-P).

**Comment by sarayourfriend** [comment]
If you need to mock on the socket level, [`python-mocket`](https://github.com/mindflayer/python-mocket) is precisely for that purpose, and may suit you well.

**Comment by piranna** [comment]
> If you need to mock on the socket level, [`python-mocket`](https://github.com/mindflayer/python-mocket) is precisely for that purpose, and may suit you well.

Didn't know that, thanks for the advice :-)
