### ISSUE TITLE
Running `hatch run test:test` results in "Failed building wheel for brotlicffi" on macOS

### ISSUE THREAD

**Issue by rsmeral** [h2non/pook#159]
Running `hatch run test:test` results in "Failed building wheel for brotlicffi". See [error-log.txt](https://github.com/user-attachments/files/17895357/error-log.txt).

* Python 3.12.1
* MacOS (M1) 15.1.1
* `hatch` installed via `brew`
* First time installed `hatch` and first time run of `hatch run test:test`

**Comment by sarayourfriend** [comment]
Thanks for opening the issue. It looks like you ran into this bug: https://github.com/python-hyper/brotlicffi/issues/201

It might be coming from the pytest-httpbin dependency :disappointed:. httpbin hasn't been maintained in a while, so maybe it would be best to spin up a local http server some other way for the unit tests.
