### ISSUE TITLE
pip install: error in pook setup command

### ISSUE THREAD

**Issue by horida** [h2non/pook#25]
with pip install and an old version of setuptools (19.2) I get:

```
$ pip install pook
Downloading/unpacking pook
  Downloading pook-0.1.2.tar.gz
  Running setup.py (path:/home/user/repo/venv/build/pook/setup.py) egg_info for package pook
    error in pook setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in pook setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

`pip install --upgrade setuptools` solves this

Though the dependencies `xmltodict` and `jsonschema` are not installed automatically.

**Comment by h2non** [comment]
I would need more info, such as Python and `pip` versions, in order to help you here. 

I installed the package in pip 8.1.x and 9.x versions across Python 2.7+ and 3.4+.

**Comment by horida** [comment]
pip 1.5.4 
Python 2.7.6

**Comment by h2non** [comment]
You should simply upgrade pip. I don't wanna invest time providing support for old `pip` versions.
Upgrading `pip` should be frictionless in any environment.
