### ISSUE TITLE
MocketEngine is not working anymore with latest version of pook

### ISSUE THREAD

**Issue by mindflayer** [h2non/pook#42]
Hi there,
I am still looking into your last changes, but I am sure that the latest version you released few days ago broke `MocketEngine`.

**Comment by tomas-fp** [comment]
That's weird. `v0.1.x` should not introduce any behavioural change, but `v0.2.x` does:
you must explicitly enabled the mock engine calling `pook.on()`.

Can you share some code?

**Comment by mindflayer** [comment]
So, if I move the `.activate()` or `.on()` after the engine `.set_mock_engine()`, `pook` seems to work but actually the first `assert` fails.
https://github.com/mindflayer/python-mocket/blob/master/tests/tests27/test_pook.py

**Comment by mindflayer** [comment]
Everything was fine before `0.2.0`, as you can see:
https://travis-ci.org/mindflayer/python-mocket/builds/204521062

**Comment by tomas-fp** [comment]
I think this line is fucking us due to be default behavior change:
https://github.com/h2non/pook/blob/master/pook/engine.py#L78-L79

I can't debug things now in my laptop, but will do later tonight! I think there's no needed action from your side.

**Comment by mindflayer** [comment]
Yes, I was looking at the same rows. :)

**Comment by h2non** [comment]
Well, this should be fixed in `pook@v0.2.1`, but I think there's an implicit limitation in the `mocket` engine implementation that does not allow registering it at global level, which is very handy.

This code works:
```js
import pook
import requests
from mocket.plugins.pook_mock_engine import MocketEngine

# NOTE: this will not work and should be revised
# pook.set_mock_engine(MocketEngine)


@pook.on
def test_pook_engine():
    # Use Mocket as mock engine
    pook.set_mock_engine(MocketEngine)

    url = 'http://twitter.com/api/1/foobar'
    status = 200
    response_json = {'error': 'foo'}

    mock = pook.get(
        url,
        persist=True,
        reply=status,
        response_json=response_json,
    )

    requests.get(url)
    assert mock.calls == 1

    resp = requests.get(url)
    assert resp.status_code == status
    assert resp.json() == response_json
    assert mock.calls == 2


if __name__ == '__main__':
    test_pook_engine()
```

**Comment by mindflayer** [comment]
I changed nothing, and it used to work before your changes. Dunno if I can
really help.
Suggestions?

Il 26 mar 2017 12:59 AM, "Tomás Aparicio" <notifications@github.com> ha
scritto:

**Comment by tomas-fp** [comment]
What's I'm suggesting is that with the idiomatic way to enable `pook` you need to move [these lines](https://github.com/mindflayer/python-mocket/blob/master/mocket/plugins/pook_mock_engine.py#L45-L58) in your implementation when the mocks are actually triggered and exists.

Currently, no mocks will be registered because you're registering them before declaring them because of the mock engine activation order.

The idiomatic way of using `pook` would be:
```js
# Registering the mock engine at global level, once, would be the natural approach
pook.set_mock_engine(MocketEngine)

@pook.on  # -> pook will activate the underlying mock engine when the function is called but we still don't have any mock already declared
def my_test_fn():
   # Then we declare our mocks
   pook.get('foo.com', reply=404)
   pook.get('bar.com', reply=404)

   # Then we run our requests
   requests.get('http://foo.com')
   requests.get('http://bar.com')
   
   # After function execution, we're done!
```

**Comment by tomas-fp** [comment]
If you change the declaration order and you register your mocks before calling `pook.on`, I'm sure it will work!

**Comment by mindflayer** [comment]
I totally agree and I've already a change. ;)

**Comment by mindflayer** [comment]
Here we go:
https://github.com/mindflayer/python-mocket/blob/master/mocket/plugins/pook_mock_engine.py

**Comment by mindflayer** [comment]
Latest version has better support for pook.
https://github.com/mindflayer/python-mocket/releases/tag/1.8.0

**Comment by h2non** [comment]
Cool! Thanks!
