### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by idantene** [h2non/pook#58]
Heya.
After playing a bit with the library (well done!), I've found that, at least on Python 3.7 (which is now officially released), then `pook.off()` doesn't work.
Moreover, `enable_network` (with and without hosts) doesn't work. Without host there just seems to be no effect (still raises exception on unmatched requests), and with hosts it yells about incompatibility between a tuple and a list/string.

Would be happy to help fixing these if needed!

**Comment by h2non** [comment]
This should be fixed in latest release!
